spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MySQL
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    defer-datasource-initialization: true