spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: service-auth
            uri: lb://service-auth
            predicates:
              - Path=/api/auth/**

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/