spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: service-user
            uri: lb://service-user
            predicates:
              - Path=/api/users/**

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/