spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Global Filter!!
            preLogger: true
            postLogger: true
      routes:
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/api/users/**
            - Header=test,test1

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/